name: Zip and Upload to S3

on:
  push:
    branches:
      - main
      - experimental

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create code.tar.gz
        run: |
          tar --exclude='.git' --exclude='.github' --warning=no-file-changed -czf code.tar.gz . || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Set S3 key based on branch
        id: s3key
        run: |
          if [ "${{ github.ref_name }}" = "experimental" ]; then
            echo "S3_KEY=experiments/code.tar.gz" >> $GITHUB_ENV
          else
            echo "S3_KEY=main/code.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload to S3
        run: |
          aws s3 cp code.tar.gz s3://${{ secrets.S3_BUCKET_NAME }}/$S3_KEY
